### ISSUE TITLE
New term request: 'blood plasma PCORnet specimen source value name', 'cerebrospinal fluid PCORnet specimen source value name', 'vagina PCORnet specimen source value name', 'cervix PCORnet specimen source value name', and 'pericardial fluid PCORnet specimen source value name'

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#16]
label: blood plasma PCORnet specimen source value name
definition: A PCORnet specimen source value name that is about some specimen of blood plasma.
comment: The use of 'value name' in the label is a product of PCORnet calling these identifiers "value names."
term editor: Matthew Diller
contributor: William R. Hogan

label: cerebrospinal fluid PCORnet specimen source value name
definition: A PCORnet specimen source value name that is about some specimen of cerebrospinal fluid.
comment: The use of 'value name' in the label is a product of PCORnet calling these identifiers "value names."
term editor: Matthew Diller
contributor: William R. Hogan

label: vagina PCORnet specimen source value name
definition: A PCORnet specimen source value name that is about some vaginal specimen.
comment: The use of 'value name' in the label is a product of PCORnet calling these identifiers "value names."
term editor: Matthew Diller
contributor: William R. Hogan

label: cervix PCORnet specimen source value name
definition: A PCORnet specimen source value name that is about some cervical specimen.
comment: The use of 'value name' in the label is a product of PCORnet calling these identifiers "value names."
term editor: Matthew Diller
contributor: William R. Hogan

label: pericardial fluid PCORnet specimen source value name
definition: A PCORnet specimen source value name that is about some specimen of pericardial fluid.
comment: The use of 'value name' in the label is a product of PCORnet calling these identifiers "value names."
term editor: Matthew Diller
contributor: William R. Hogan

**Comment by sjbost** [comment]
I noticed that these don't have axioms or superclasses. Is that intentional?

**Comment by dillerm** [comment]
We haven't made any axioms for them and I'm not sure we intend to. As far as the superclasses go, I think I just forgot to add them. They all have the same parent class of 'PCORnet specimen source value name'.
