### ISSUE TITLE
Term request: 'patient PCORnet specimen source value name' and 'provider PCORnet specimen source value name'

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#17]
label: patient PCORnet specimen source value name
alternative terms: none
textual definition: A PCORnet specimen source value name that is about a patient.
definition source: none
comment 1: This value name is not about an actual specimen.
comment 2: The LOINC codes that this value name applies to are 59768-2 (Procedure indications [Interpretation] Narrative), 32624-9 (Race), 56850-1 (Interpretation and review of laboratory results), and 56794-1 (Internal identifier).
logical definition: subclass-of PCORnet specimen source value name
term editor: Matthew Diller
contributors: William R. Hogan

label: provider PCORnet specimen source value name
alternative terms: none
textual definition: A PCORnet specimen source value name that is about some identifier that denotes a physician.
definition source: none
comment 1: This value name is not about an actual specimen.
comment 2: The PROVIDER value name might denote something other than a physician identifier, like a telephone number, depending on the data source. We limit it to being about an identifier that denotes a physician because this is what our data sources apply the value name to.
logical definition: subclass-of PCORnet specimen source value name
term editor: Matthew Diller
contributors: William R. Hogan

**Comment by CDowland** [comment]
I have now added these terms to the development branch.
