### ISSUE TITLE
Import (MIREOT) BFO's 'temporal interval' and 'temporal region'

### ISSUE THREAD

**Issue by CDowland** [ufbmi/PCORowl#18]
Import 'temporal interval' and 'temporal region' the BFO 2020 OWL file, as found here: https://standards.iso.org/iso-iec/21838/-2/ed-1/en/owl/bfo-2020.owl.

**Comment by CDowland** [comment]
This task is complete.

**Comment by sjbost** [comment]
@CDowland I actually had a question about this that didn't get to at our Moonshot meeting yesterday. Does PCORowl import a different BFO owl file in its entirety? If so, should we replace that import with the BFO 2020 owl file as opposed to MIREOTing in specific classes?

**Comment by CDowland** [comment]
I saw that you had that question on the agenda. It's a good question, and since it should be answered before I moved forward on this, I asked Bill about it during our one-on-one meeting yesterday. He said that, for now at least, we'll just do these classes.

**Comment by sjbost** [comment]
Thanks for checking on that!
