### ISSUE TITLE
Create OWL Individuals for procedure code sets

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#19]
One individual is needed for each of the following:

label: International Classification of Diseases, Ninth Revision, Clinical Modification
alternative term: ICD-9-CM
instanceOf: code set

label: International Classification of Diseases, Tenth Revision, Procedure Coding System
alternative term: ICD-10-PCS
instanceOf: code set

label: Current Procedural Terminology
alternative term: CPT
instanceOf: code set

label: Healthcare Common Procedural Coding System
alternative term: HCPCS
instanceOf: code set

label: Uniform Billing 04 Form Locator 42 Revenue Codes
alternative term: UB-04 FL 42 Revenue Codes
instanceOf: code set

**Comment by CDowland** [comment]
I just noticed there is already a version of the first one, with exactly the same label. It also has a definition and definition source. Also, we currently have a subclass of 'code set' that is 'International Classification of Diseases,' though there is nothing to it other than its label and parent class.

I could either replace the current individual with this, or just add the alternative term and its type. Which shall we do?

Also, shall we give the first two 'code set' as the type, or use 'International Classification of Diseases'?

**Comment by sjbost** [comment]
In 9/23 Moonshot Aim 4 meeting, decided to revise existing ‘International Classification of Diseases, Ninth Revision, Clinical Modification’ to instanceOf: code set; add alternative term: ICD-9-CM; retain existing definition and definition source.

**Comment by CDowland** [comment]
Done.
