### ISSUE TITLE
Fix annotation on 'admission process'

### ISSUE THREAD

**Issue by dillerm** [ufbmi/PCORowl#9]
Currently the definition is in a definition source annotation

**Comment by CDowland** [comment]
All PCORnetCDM.owl annotations for the OMRSE term 'patient discharge' have been removed, and the OMRSE version will soon have a definition, etc. As for 'admission process,' it will soon be deprecated in PCORnetCDM.owl and will be added to OMRSE, a more appropriate home ontology for it. So, I am closing this issue.
